package com.front.cerror;

public enum ErrorType {
    NO_SUCH_DECL,
    EXPECT_TOKEN,
    UNEXPECTED_TOKEN,
    CONST_FAIL,
    INVALID_CONST_LIST,
    EXP_PARSE_FAIL,
    ARRAY_DIM_ERROR,
    FUNC_PARAM_FAIL,
    WRONG_RETURN_TYPE,
    TYPE_MISMATCH,
    ASSIGN_TO_CONST,
    IDENT_NOT_EXISTS,
    NOT_A_THREAD,
}
